infos=[
	{name:"本吧管理组",id:"admins",init:fill_admin,content:[
		["吧主",['飞翔的天地','关签','御坂美琴みさか']],
		["小吧",['陆umj','幻の上帝','夜雨の离殇','寒云似雾','一群牛跑过','ZD_Tinson','RichSelian','EAgleLeo','LH_Mouse_Ex','NEMESIS_T2']],
		["小编",['一群牛跑过','菲西卡斯']],
	],expanding:true},
	{name:"本吧吧规",id:"rules",init:fill_rule,content:[
		['体例说明',
			'* \'*\'为注释/tips；<b>粗体</b>表示强调；<i>斜体</i>表示约定的术语；<a href="http://zh.wikipedia.org/zh-cn/%E6%B5%B7%E8%B2%93%E9%B3%B4%E6%B3%A3%E6%99%82#.E7.94.A8.E8.AF.AD.E8.A7.A3.E8.AF.B4" target="_blank"><font style="color:red;">红字</font></a>表示真实的警示。',
			'* 部分文字以链接的形式提供相关解释或资源引用作为补充说明。若术语存在约定，含义以本吧规正文为准。',
			'* 吧务对吧规保留著作权。',
			'* 使用<a href="http://zh.wikipedia.org/wiki/Git" target="_blank">Git</a>获取本页的修订<a href="https://github.com/tieba/tieba.github.com/tree/master/cpp" target="_blank">历史记录</a>。',
			'* 建议使用<a href="https://github.com/tieba/tieba.github.com/issues?state=open" target="_blank">Issue</a>和<a href="https://github.com/tieba/tieba.github.com/pulls" target="_blank">Pull Request</a>反馈对本页的意见和建议。',
			'* 最后修订：2013年7月13日。'
		],
		['总则',
			'1.1 为保障吧友的正当权益，明确吧务的管理职责，促进良好的讨论气氛，根据<a href="http://tieba.baidu.com/tb/eula.html" target="_blank">百度《贴吧协议》</a>和<a href="http://tieba.baidu.com/tb/system.html#cnt08" target="_blank">《百度贴吧吧主制度》</a>，制定本吧规。',
			'1.2 本吧规适用于<b>百度C++吧（以下称“<i>本吧</i>”）</b>，自公布即日起施行。',
			'1.3 请自觉遵守百度贴吧协议。',
			'1.4 注意言行，尊重他人就是善待自己。',
			'1.5 切勿打击新手，明白强者二字的真正含义。',
			'1.6 <a href="http://baike.baidu.com/view/1107286.htm" target="_blank"><i>IP党</i></a>无人权。'
		],
		['吧务管理',
			'2.1 <i>吧务</i>（本吧管理组）按《百度贴吧吧主制度》和本吧规行使管理本吧的职权。本吧也欢迎其他吧友协助吧务进行管理，共同维护良好的讨论秩序。',
			'2.2 <i>违规行为</i>包括违反中华人民共和国法律法规、百度贴吧协议和本吧规其它条款明令禁止的事项。',
			'2.3 吧务在有合理的理由和符合本吧规规定的前提下拥有以个人观点管理本吧的权利。合理的理由包括但不限于对违规行为的处理。',
			'2.4 吧务在有必要时可以通过利用贴吧系统授权的操作进行管理。操作涉及处理的对象（<a href="http://baike.baidu.com/view/2410019.htm" target="_blank"><i>相对人</i></a>）包括<a href="http://baike.baidu.com/view/22657.htm" target="_blank"><i>当事人</i></a>的贴吧<i>ID</i>、能被证明直接有关联的一个或多个<i>傀儡账户</i>（“<i>马甲</i>”）或IP等。吧务管理本吧的操作包括警告、删贴（删除主题和/或回复）、封禁、添加黑名单等。',
			'2.5 吧务应删除构成违规行为的内容；或在存在充分理由时，指出违规后予以暂时保留。',
			'2.6 对于初次违规的吧友，吧务应进行警告。无视警告再犯者和屡教不改者应考虑封禁。故意违规、破坏吧务管理者封禁并加入黑名单。',
			'2.7 吧务在管理本吧、涉及对被管理者的操作时可以不提前通知相对人，但有义务回答吧友关于操作的询问，包括执行管理操作的理由。',
			'2.8 吧务人员的共识代表吧务的整体意见。吧务人员意见有分歧时，首先以本吧规的明文规定为准，协商解决。',
			'2.9 对吧规或管理有疑问、查询操作记录或请求对贴子进行删除、恢复和加精等事宜，请<a href="#contacts">自行联系</a>吧务。'
		],
		['讨论形式',
			'* 提问请先看：<a href="/common/howtoask.html" target="_blank">提问的艺术</a>。',
			'3.1 本吧主题为C++及其它程序设计、软件开发、计算机科学和相关基础学科的一般话题，包括但不限于疑问求助、技术讨论、书籍评论、成果展示、行业新闻等。',
			'3.2 为维护讨论秩序，本吧贴子列表首页的内容一般应主要为近期活跃的和本吧主题相关的讨论内容。对此造成不利影响的行为视为<i>影响版面</i>。影响版面的主题或回复由吧务定性，视情况予以保留或删除，但不得以此为由封禁。',
			'3.3 <i>吧务贴</i>是对吧务人员、管理操作和吧规制定及解释直接相关的讨论或吧务对此的公告。',
			'3.4 除非能证明吧务管理存在过错，公开质询吧务的吧务贴被视为影响版面。',
			'3.5 讨论内容不属于本吧主题及相关内容，没有构成违规行为，也不是吧务贴的贴子为<i>水贴</i>。',
			'3.6 本吧不禁止水贴，但请注意节制，保持适当有意义的内容。不要过于频繁发水贴。',
			'3.7 通过回复、点“赞”等方式使贴子出现在首页上方的行为为<i>顶贴</i>。',
			'3.8 主题或最后回复在一个自然月前的贴子为<i>坟贴</i>。对坟贴的顶贴为<a href="http://baike.baidu.com/view/705635.htm"><i>挖坟</i></a>。',
			'3.9 同一个ID在短时间内重复（连续或可认为有意连续，下同）发布相同的内容主题或回复，吧务应视情况保留其一。不同ID在短时间内发布相同的内容（“<i>撞车</i>”），吧务应视情况删除或保留。',
			'3.10 本吧内贴子删除功能应仅用于维护正常讨论秩序，即删除明显的违规、重复或另有约定的内容，不得用于在吧规许可的范围外作为限制特定吧友发言的手段。',
			'3.11 发布主题贴的<i>楼主</i>（可被简称<i>LZ</i>等）对主题内容负责，有权对主题内偏离主旨的讨论作出提醒，但在吧规允许外不得以此为由擅自删除内容。',
			'3.12 对于较长的主题文章多个连续回复进行发布时，为预防打断文章内容的<i>插楼</i>（不含楼中楼）回复，楼主可在前10楼内发布醒目提示预告删除插楼者。预告在24小时内文章内容未宣布发布完全时，对吧务操作内容以外的实际插楼内容及其楼中楼有效，即删除不需要提供其它理由。',
			'3.13 在本吧删除未被禁止的正常回复的，若能提供证据，吧友有权要求删除者解释；确认误删的，吧主应予以恢复；无合理理由删除的，吧务可视情况对删除者予以警告或封禁。'
		],
		['禁止事项',
			'4.1 以下行为无条件视为违规行为：作弊；伸手；侵权；不文明言行（包括ID中出现的侮辱性称谓）；吧务调解无效、无视警告仍然继续的争吵。',
			'4.2 以下行为视为违规行为，除非提前通知并得到吧务批准：拜师；对非精品主题的挖坟；广告；使用仿冒吧务的ID；标题长度不大于2个字符的主题贴；贴子标题故意出现吸引目光的字符（如火星文）；贴子标题或内容出现大片重复或无意义文本；要求回复留邮箱分享资源。',
			'4.3 散布和本吧主题相关的、能通过权威依据查证明确的错误内容，教唆学习错误内容，可预见或已经产生严重误导的贴子内容会视情节被警告或作为违规行为。',
			'4.4 本吧不支持作弊行为，所有考试求助贴一律删除。',
			'4.5 广告内容不分私人广告和商业广告（包括QQ群、论坛的推广等），一律删除。对和本吧主题相关的贴吧贴子和个人项目的宣传，吧务可根据具体内容不视为广告。',
			'4.6 过于影响版面的水贴会被删除。',
			'4.7 过于影响版面的或有意的多次挖坟应被封禁。',
			'4.8 以下附则中规定的（典型）<a href="#rules-violation-example">违规样例</a>。',
			'4.9 凡回复中使用复制的长篇无意义的用来赚取经验的内容将被删除'
		],
		['发贴建议',
			'5.1 发代码者请注意自己的代码格式。注意百度一般无法保证代码的缩进和对齐，对阅读带来不便时应该尽量避免直接贴代码。替代手段：短代码请贴'
				+'<a href="http://gist.github.com/" target="_blank">Gist</a>'
				+' | <a href="http://codepad.org/" target="_blank">Codepad</a>'
				+' | <a href="http://ideone.com/" target="_blank">Ideone</a>'
				+' | <a href="http://pastebin.com/" target="_blank">Pastebin</a>'
			+'，长代码或项目文件推荐公开的在线代码托管服务，如'
				+'<a href="http://github.com">GitHub</a>'
				+' | <a href="http://bitbucket.org">BitBucket</a>'
				+' | <a href="http://code.google.com">Google Code</a>'
			+'；或网盘（如<a href="http://pan.baidu.com">百度网盘</a>）。',
			'5.2 把本文看完，然后看一遍《提问的艺术》。',
			'5.3 多用搜索引擎(<a href="http://www.google.com">Google</a>)和专业的论坛(<a href="http://stackoverflow.com">StackOverflow</a>...)',
			'5.4 在提问前尝试自己解决问题。例如编译失败多数是由于自己的粗心大意造成的，自己读编译器输出的诊断消息就能解决。',
			'5.5 在提问贴中说明自己做出的努力（不需要长，例如把自己的代码或者思路写下来，已经搜索过的关键字等）。',
			'5.6 注意表达的清晰简洁。长且不带任何注释说明的代码容易让人不适。请给出关键的代码，或指出可能造成问题的部分。',
		],
		['<a name="contacts">联系方式</a>',
			'6.1 本吧官方群：19782472（其中有一堆基佬），不定期开放申请。',
			'6.2 善用<a href="http://msg.baidu.com">私信</a>。',
			'6.3 合理使用贴吧的at（“@”+ID）功能。'
		],
		['<a name="rules-violation-example">违规样例</a>',
			'<font style="color:red;"><b>凡发以下类型贴者，十天循环小黑屋+黑名单不送。</b></font>',
			'A.1 请问我不会数学英语可以学C++吗？回答不可以的滚。',
			'A.2 我xxxx可以学C++吗？（xxxx=现在初二/现在高二/大学毕业了/工作了/是女生/残疾人/蛋痛了/...）',
			'A.3 wqnmlgb',
			'<font style="color:red;">凡发以下类型贴者，请去小黑屋待上一天。</font>',
			'B.1 请问这段代码哪里有错？',
			'B.2 请问C++怎么学？',
			'B.3 请问谭XX的书可以吗？',
			'B.4 请问这题怎么写？',
			'B.5 请问这段代码什么意思？要求简洁易懂。',
			'B.6 有没有C++QQ群？',
			'B.7 小女子请问xxxxxx？'
		]
	],expanding:true},
	{name:"权威资源",init:fill_info,content:[
		["http://www.open-std.org/jtc1/sc22/wg21/","The C++ Standards Committee","ISO/IEC JTC1/SC22/WG21"],
		["https://github.com/cplusplus/draft","C++ standards drafts","ISO/IEC JTC1/SC22/WG21"],
		["http://isocpp.org/","Standard C++ homepage", "Standard C++ Foundation"],
		["https://groups.google.com/a/isocpp.org/forum/#!topic/std-discussion","ISO C++ Standard - Discussion", "Standard C++ Foundation"],
		["https://groups.google.com/a/isocpp.org/forum/#!forum/std-proposals","ISO C++ Standard - Future Proposals", "Standard C++ Foundation"],
		["http://accu.org/","ACCU","ACCU"],
		["http://www2.research.att.com/~bs/","Bjarne Stroustrup's homepage","Bjarne Stroustrup"],
		["http://herbsutter.com/gotw/","GotW(Guru of the Week) for C++11","Herb Sutter"],
	],expanding:true},
	{name:"概念与纠错",init:fill_link,content:[
		["http://tieba.baidu.com/p/1051426693","[原创]《高质量C++/C编程指南》陷阱","幻の上帝"],
		["http://tieba.baidu.com/p/1411238421","ISO C的一些基本概念","幻の上帝"],
		["http://tieba.baidu.com/p/1422487681","ISO C11附录C","幻の上帝"],
		["http://tieba.baidu.com/p/1758580031","[科普]字符串和字符串的长度","幻の上帝"],
		["http://tieba.baidu.com/p/1912906851","[原创][科普]面向对象和所谓的“面向过程”","幻の上帝"],
		["http://tieba.baidu.com/p/1969958655","关于main函数的原型和返回值(void main vs int main)","幻の上帝"],
		["http://tieba.baidu.com/p/2021793275","[原创]C/C++语言学习导论(1)","幻の上帝"],
		["http://tieba.baidu.com/p/2023656913","[原创]C/C++语言学习导论(2)","幻の上帝"],
		["http://tieba.baidu.com/p/2091426198","[原创]C11&C++11的赋值相关表达式求值","幻の上帝"],
		["http://tieba.baidu.com/p/2092647737","百度百科低质量相关词条内容通告","幻の上帝"],
		["http://tieba.baidu.com/p/2201116330","关于异常处理的一些话题","幻の上帝"],
	]},
	{name:"语言设计和演化",init:fill_link,content:[
		["http://tieba.baidu.com/p/1025389624","c++0x右值引用,你怎么吃了一半就走了?","陆umj"],
		["http://tieba.baidu.com/p/1026523474","c++0x右值引用,你怎么吃了一半就走了?(续)","陆umj"],
		["http://tieba.baidu.com/p/2272468675","[原创][科普]C&C++广义类型系统缺陷","幻の上帝"],
		["http://tieba.baidu.com/p/2403773958","[原创]转移vs复制","幻の上帝"],
	]},
	common_info.contact, // 友情贴吧&联络方式
	common_info.books, // 书籍介绍
	common_info.hardware, // 硬件介绍
	common_info.operating_system, // 操作系统
	common_info.software, // 软件介绍
	{name:"新手教程(C语言吧)",init:fill_link,content:[
		["http://tieba.baidu.com/p/1165625989","解读御坂美琴みさか的菱形打印程序——谈如何学习算法","咱是仙人"],
		["http://tieba.baidu.com/p/1109535412","xxx管理系统(作业党你们懂的,伸手杀无赦)","RichSelian"],
		["http://tieba.baidu.com/p/1098980046","教你构建MinGW＋Notepad++编程环境 for C/C++","5B4B铅笔"],
		["http://tieba.baidu.com/p/1570864020","调试指南(问问题之前请自重)","九头一存"],
		["http://tieba.baidu.com/p/1393147869","链表","万能姬"],
		["http://hi.baidu.com/misaka20001/item/d4a4144036d5fbefbdf451de","[文]某吧主的学习经历","御坂美琴みさか"],
		["http://tieba.baidu.com/f/good?kw=c%2B%2B","更多请阅读'本吧精品区'",""],
	]},
	{name:"原创翻译",init:fill_link,content:[
		["http://tieba.baidu.com/p/1639526628","【译制】入门向：VC++ 中的 Lambda 表达式","candy76041820"],
		["http://tieba.baidu.com/p/1802993336","[原创][翻译]为什么每个C程序员应该了解未定义行为#1","幻の上帝"],
		["http://tieba.baidu.com/p/1803801220","【译制】每个 C 程序员都应知道的关于未定义行为的那点事","candy76041820"],
		["http://tieba.baidu.com/p/1865399306","【译制】“‘差劲更好’对‘正确的事’”：到底要说啥来着？","candy76041820"],
	]},
	common_info.project, // 吧友作品(项目)
	{name:"吧友作品(C语言吧)",init:fill_link,content:[
		["http://tieba.baidu.com/p/1535637800","四则计算器(其实人都是慢慢改进的)","c_vs"],
		["http://tieba.baidu.com/p/1894817975","LL1表达式计算器","御坂美琴みさか"],
		["http://tieba.baidu.com/p/1977678397","拼图游戏","忆_碎碎念"],
	]},
	{name:"吧友语录",init:fill_about,content:[
		["patricia_xiao:谭书",[
			"前不见古人后不见来者念天地之悠悠独怆然而泪下。",
			"真是高端洋气上档次。哈、哈、哈。",
			"【= =←注意看表情】",
			"你们老师挺能跟风的。",
			"不过没关系，我们老师也很能跟风，这本也是什么参考书之一。没关系。不看就好了。在下有一柜子的相关书籍，不怕它。不碰它。不搭理它。",
			"只是纠结一件事，根据【薪火相传】远离，在下有义务赠书于下一级。那么，是销毁这本书避免它荼毒众生呢，还是传下去呢。唉，好伤脑筋。",
		].join("<br>")]
	]},
	{name:"人物简介&马甲",init:fill_person,content:[
		["幻の上帝/FrankHB","圆滚滚的工口帝球葱[<a href=\"https://bitbucket.org/frankhb/\" target=\"_blank\">frankhb</a>][<a href=\"https://github.com/FrankHB\" target=\"_blank\">FrankHB</a>]"],
		["RichTextBox/RichSelian/EGG娘","ROX-滚床压缩肉牛[<a href=\"https://github.com/richox\" target=\"_blank\">richox</a>]<sub>妹纸：某度娘HR //FIXME: @NailesHcir</sub>"],
		["Hope_20121221_","某个小正太[<a href=\"https://github.com/hope1\" target=\"_blank\">hope1</a>]"],
		["寒云似雾/灵风竹/TetrisNoOSer","某个大水笔葱[<a href=\"https://github.com/hysw\" target=\"_blank\">hysw</a>]"],
		["关签","灿烂的大菊<sub>花</sub>长"],
		["飞翔的天地",""],
		["LH_Mouse_EX/乐天派的小耗子","玩窗户<sub>Win</sub>的耗吱"],
		["NEMESIS_T2",""],
		["Padme0Amidala","某著名大水笔"],
		["御坂美琴みさか/EGE娘","misaka-传说中的炮姐[<a href=\"https://github.com/misakamm\" target=\"_blank\">misakamm</a>]"],
		["⑨chu","[<a href=\"https://github.com/9chu\" target=\"_blank\">9chu</a>]"],
		["EAgleLeo",""],
		["ZD_Tinson",""],
		["whatofor",""],
		["life_stolen",""],
		["星月and圣冰雨","算法大牛"],
		["HGtz2222",""],
		["china_gll",""],
		["傻渡娘","<sub>汉纸：啪啪熊</sub>"],
		["卩s灬飞飞",""],
		["jingyingbox",""],
		["_craftG/良化纲领_/阎魔抽/serviper/九头一存/帕斯科维/H之读姬/Razielize/oxdead/Raptor酱/扯蛋的Aria/Xenoneee/九重束风景/攻城尸_/万能姬/守尸神主/...","撸之羊驼[<a href=\"https://github.com/Akvelog\" target=\"_blank\"fi>Akvelog</a>]"],
		["User32","被揉坏掉了的冰凉小脸"],
		["萧の十三郎",""],
		["风之追梦者/梅汁追求者",""],
		["陆umj",""],
		["wysaid","好像在搞3D(gl还是dx)似得"],
		["凤凰院红旗/赫斯珀罗斯/战地3/秽语/某内核的开发者","水货一枚[<a href=\"https://github.com/HououinRedflag\" target=\"_blank\">HououinRedflag</a>]"],
		["Coding狂人","好似很久以前被气走了"],
		["阿宾和白洁","已经彻底坏掉了"],
		["矮油嫑酱紫唉","法律<sub>好似是婚姻法</sub>人士在这里"],
		["5230娘/顶之座__赫卡特/灼发の夏娜","hecate/彩夏/ayaka/毛球<sub>日语巨触</sub>"],
		["汇蓝鸟","英文+图形+... <- 面麻<sub>酱</sub>似乎快无敌了"],
		["assiss","C语言吧元老<sub>似乎有女儿以后就很少来了……</sub>"],
		["Lemoneee/Gilliland/SergeiSobolev/...","好久没出现的G算姬[<a href=\"https://github.com/Golevka\" target=\"_blank\">Golevka</a>]"],
		["彩色の夢∩o∩","数学娘、别字娘、正体字娘"],
		["怪兽大战魔人","编译器大神"],
		["Luoji_1995","GJK-逻辑神最近不知道去哪了"],
		["NaylonSlain","<sub>好久不见... 忘了擅长...</sub>"],
		["MasterRay","<sub>话说由于某云来的晚，所以不太清楚... 知道的写一下介绍</sub>"],
		["8pm","<sub>话说由于某云来的晚，所以不太清楚... 知道的写一下介绍</sub>"],
		["gccer","<sub>话说由于某云来的晚，所以不太清楚... 知道的写一下介绍</sub>"],
		["CIW_BLUE","<sub>话说由于某云来的晚，所以不太清楚... 知道的写一下介绍</sub>"],
		["nadesico19","C菌-日语巨触[<a href=\"https://github.com/nadesico19\" target=\"_blank\">nadesico19</a>]"],
		["","ps@hysw. 喂喂喂.... 不能总是只有我写阿..."],
		["Laconism","简练之格言[<a href=\"https://github.com/laconism\" target=\"_blank\">laconism</a>]"],
		["patricia_xiao/Carbucketty","<sub>腋潇</sub>"],
		["",""],
	]},
	{name:"给新手的Q&amp;A",init:fill_qa,content:[
		["我现在在读xx[学校/年级...]，能不能C++",
			"能: 如果你愿意<i>浪费</i>时间在程序的苦海之中, 有兴趣坚持走下去, 并且有一定的数学基础"+"<br>"+
			"不能: C++对于很多人而言<b>真的很难</b>"+"<br>"+
			"你可以去学,学不学得了是你自己的问题"
		],
		["学C++该如何入门","看书, 读代码, 敲代码, Wikipedia, csdn, 本吧精品区, Google, Bing, Baidu"],
		["为神马推荐《C Primer Plus》而不推荐销量干万的《C程序设计》","不是说崇洋媚外，不是外国书就没错误了，只是《C程序设计》的概念性错误太多了"],
		["看完了谭的《C++程序设计》(或类似)请问下一步该做什么",
			["考二级: 够了，不用学别的了","学校课程要求的，以后不用: 随你","学了要用的: 好吧[扔掉/烧掉/埋掉]随你,具体请看'书籍简介'"].join("<br>")
		],
		["C语言,C++,Java,Python,XXX,YYY改如何选择","自己试去<sub>ps.其实Python是个不错的入门选择</sub>"],
		["怎么样逃离可怕的黑框框","命令行挺好的，实在要图形的话自己去搜GUI/D3D/GDI/OpenGL/QT/GTK..."],
		["关于(i++)+(++i),printf(\"%d%d%d\",++i,i,i++),i+=i*=i","警告: 别写(除了某些特殊情况,没人能保证这些类型的玩意会出现神马问题,参见《C陷阱与缺陷》)"],
		["C++有前(钱)途么","看你学的怎么样&找的工作怎么样"],
		["32/64位Windows xp/7/8该用神马软件","集成开发环境介绍的基本都可以"],
		["找VC6?为什么不应该用VC6，以及为什么VC6的兼容性如此之差","和Window98同样的道理(话说XP都到该被淘汰的时候了)"],
		["有什么图形库","EGE神马的挺好的(参见吧友作品)"],
		["学C++要多久","21天"],
	]},
	{name:"各种教程(C语言)",init:fill_link,content:[
		["http://tieba.baidu.com/p/1597468718","适合新手练习的几个题目，控制台不再单调呵呵（持续更新）","Geodesic"],
		["http://tieba.baidu.com/p/2025276932","对拼图问题可还原性的探究","忆_碎碎念"],
		["http://tieba.baidu.com/p/2007516908","C语言递归调用转化为栈处理的一般式","elf0223"],
		["http://tieba.baidu.com/p/2092645577","辅助的原理","霸气外露真没有"],
		["http://tieba.baidu.com/p/1313731304","C语言180行随机迷宫代码 详解+分析","追忆曾经_"],
		["http://tieba.baidu.com/p/1360685329","扫雷","wysaid"],
		["http://tieba.baidu.com/p/1972512091","〔九重的百物语之二〕A cellular compiler","守尸神主"],
		["http://tieba.baidu.com/p/1797769781","【新手进阶】话说那些聊天与游戏的网络交互实现","汇蓝鸟"],
		["http://tieba.baidu.com/p/1798139204","【初入老鸟】那些网游外挂中大大小小的远程call","汇蓝鸟"],
		["http://tieba.baidu.com/p/1852969320","【游戏编程】构架游戏中的粒子系统","汇蓝鸟"],
		["http://tieba.baidu.com/p/1795338852","【新手教程】用C语言制作单机游戏外挂","汇蓝鸟"],
		["http://tieba.baidu.com/p/1868393695","【音乐编程】基于DirectSound的音乐播放与FFT频谱可视化(part 1)","汇蓝鸟"],
		["http://tieba.baidu.com/p/1885477077","【音乐编程】基于DirectSound的音乐播放与FFT频谱可视化(part 3)","汇蓝鸟"],
		["http://tieba.baidu.com/p/1906977428","【音乐编程】播放器频谱可视化与语音的智能识别思想(part 3)","汇蓝鸟"],
		["http://tieba.baidu.com/f/good?kw=c%D3%EF%D1%D4","更多请阅读'本吧精品区'",""],
	]},
	common_info.about_NCRE2, // 关于二级
	common_info.about_Tan, // 关于谭书
	{name:"其他(C语言)",init:fill_link,content:[
		["http://tieba.baidu.com/p/13382217","原问题资料大全","vc99"],
		["http://tieba.baidu.com/p/1620654727","螺旋方阵","寒云似雾"],
		["http://netlib.bell-labs.com/cm/cs/pearls/index.html","《编程珠玑》(适合有一定数据结构和算法基础的)",""],
		["http://c-faq-chn.sourceforge.net/","C语言常见问题集/495个C语言问题",""],
	]},
	{name:"Credits",init:fill_link,content:[
		["http://tieba.baidu.com/p/1941867601","IRC频道","..."],
		["https://github.com/tieba/tieba.github.com","本页源码","寒云似雾"],
		["https://github.com/","Hosted on GitHub Pages &mdash; Theme by <a href=\"http://twitter.com/#!/michigangraham\">mattgraham</a>",""],
	]},
]
