infos=[
	{name:"集成开发环境",init:fill_info,content:[
		["http://www.microsoft.com/visualstudio/en-us/products/2010-editions/visual-cpp-express","MS Visual C++ 2010 Express","微软出品的C/C++ IDE (Warning:2~4GB)"],
		["http://www.codeblocks.org/","Code::Blocks","开放源码的全功能的跨平台C/C++集成开发环境"],
		["http://www.codelite.org/","CodeLite","开源、跨平台的C/C++集成开发环境"],
		["http://sourceforge.net/projects/orwelldevcpp/","Orwell Dev-C++","可移植的C/C++IDE"],
		["http://www.eclipse.org/downloads/","Eclipse","多语言的集成开发环境(设置较为复杂)"],
		["http://netbeans.org/","Netbeans","..."],
		["http://www.geany.org/","Geany","..."],
		["http://qt.digia.com/","Qt Creator","..."],
		["http://www.prgramarts.com/cfree_ch/download.htm","C-Free","据说还可以的某个IDE (专业版收费)"],
	]},
	{name:"吧友作品",init:fill_link,content:[
		["http://code.google.com/p/comprox/","Comprox - 肉牛的压缩机","RichSelian"],
		["http://misakamm.github.com/xege/","EGE(Easy Graphics Engine) - 炮姐的图形库","御坂美琴みさか"],
		["http://tieba.baidu.com/p/1535637800","四则计算器(其实人都是慢慢改进的)","c_vs"],
		["http://tieba.baidu.com/p/1894817975","LL1表达式计算器","御坂美琴みさか"],
		["http://tieba.baidu.com/p/1941867601","C语言吧IRC频道","iyzsong"],
		["http://tieba.baidu.com/p/1977678397","拼图游戏","忆_碎碎念"]
	]},
	{name:"人物简介&马甲",init:fill_person,content:[
		["幻の上帝","圆滚滚的工口帝球葱"],
		["RichSelian/EGG娘","ROX-滚床压缩肉牛"],
		["御坂美琴みさか/EGE娘","misaka-传说中的炮姐"],
		["顶之座__赫卡特","hecate"],
		["_craftG/良化纲领_/九头一存/万能姬/守尸神主/...","羊驼-最近不知为何一直在强撸"],
		["Lemoneee/Gilliland/SergeiSobolev/...","好久没出现了"],
		["User32","被揉坏掉了的冰凉小脸"],
		["汇蓝鸟","英文+图形+... <- 面麻<sub>酱</sub>似乎快无敌了"],
		["assiss","元老"],
		["wysaid","好像在搞3D(gl还是dx)似得"],
		["彩色の夢∩o∩","<sub>话说由于某云来的晚，所以不太清楚... 知道的写一下介绍</sub>"],
		["怪兽大战魔人","编译器大神"],
		["阿宾和白洁","已经彻底坏掉了"],
		["Luoji_1995","逻辑神最近不知道去哪了"],
		["NaylonSlain","<sub>好久不见... 忘了擅长...</sub>"],
	]},
	{name:"给新手的Q&amp;A",init:fill_qa,content:[
		["我现在在读xx[学校/年级...]，能不能C语言",
			"能: 如果你愿意<i>浪费</i>时间在程序的苦海之中, 有兴趣坚持走下去, 并且有一定的数学基础"+"<br>"+
			"不能: C语言对于很多人而言<b>真的很难</b>"+"<br>"+
			"你可以去学,学不学得了是你自己的问题"
		],
		["学C语言该如何入门","看书, 读代码, 敲代码, Wikipedia, csdn, 本吧精品区, Google, Bing, Baidu"],
		["C语言,C++,Java,Python,XXX,YYY改如何选择",""],
		["为神马推荐《C Primer Plus》而不推荐销量干万的《C程序设计》",""],
		["怎么样逃离可怕的黑框框",""],
		["关于(i++)+(++i),printf(\"%d%d%d\",++i,i,i++),i+=i*=i",""],
		["C语言有前(钱)途么",""],
		["32/64位Windows xp/7/8该用神马软件",""],
		["找VC6?为什么不应该用VC6，以及为什么VC6的兼容性如此之差",""],
		["有什么图形库",""],
		["学C语言要多久",""],
	]},
	{name:"书籍简介",init:fill_info,content:[
		["http://baike.baidu.com/view/963166.htm","<<C程序设计>> <sub>谭浩强(谭老湿) 著</sub>",
			"一本挺<b>渣</b>的书,有一堆概念错误,误导性严重<sub>话说被误导的某些家伙经常会被喷的很惨</sub>"+"<br>"+
			"传说中的C语言<b>2</b>级考试<sub>真是很2的考试</sub>神书,推荐给只为了考证的同学<sub>想好好学的还是算了吧</sub>"
		],
		["http://baike.baidu.com/view/611688.htm","<<C程序设计语言>> <sub>by Kernighan &amp; Ritchie</sub>",
			"传说中的K&R C, 具有无上尊严的某书<sub>C语言的创造者的书,ANSI标准起源于此</sub>"
		],
		["","<<C Primer Plus>> <sub>by Stephen Prata</sub>","一本很经典的入门书籍<sub>据报告有不少打字错误</sub>"],
		["","<<C语言入门经典>> <sub>by Ivor Horton</sub>","据说是本很经典的入门书籍<sub>ps.本人没看过</sub>"],
		["","<<C和指针>> <sub>by Kenneth Reek</sub>","对每个学C语言的人而言都是值得一看的好书<sub></sub>"],
		["","<<C专家编程>> <sub>by Peter van der Linden</sub>","深入地讲解了C语言的一些方面<sub>看此书得有点基础</sub>"],
		["","<<C陷阱与缺陷>> <sub>by Andrew Koenig</sub>","如何不想被bug整死,请看这里<sub>看完入门书之后可以花几天先浏览一遍,排毒养颜</sub>"],
		//+c programming a modern approach
	]},
	{name:"概念与纠错",init:fill_link,content:[
		["http://tieba.baidu.com/p/1411238421","ISO C的一些基本概念","幻の上帝"],
		["http://tieba.baidu.com/p/1422487681","ISO C11附录C","幻の上帝"],
		["http://tieba.baidu.com/p/1969958655","关于main函数的原型和返回值(void main vs int main)","幻の上帝"],
	]},
	{name:"新手教程",init:fill_link,content:[
		["http://tieba.baidu.com/p/1098980046","教你构建MinGW＋Notepad++编程环境 for C/C++","5B4B铅笔"],
		//old ["http://tieba.baidu.com/p/988192757","教你构建MinGW＋Notepad++编程环境 for C/C++","5B4B铅笔"],
		["http://tieba.baidu.com/p/1570864020","调试指南(问问题之前请自重)","九头一存"],
		["http://tieba.baidu.com/p/1109535412","xxx管理系统(作业党你们懂的,伸手杀无赦)","RichSelian"],
		["http://tieba.baidu.com/p/1393147869","链表","万能姬"],
		["http://tieba.baidu.com/f/good?kw=c%D3%EF%D1%D4","更多请阅读'本吧精品区'",""],
	]},
	{name:"各种教程",init:fill_link,content:[
		["http://tieba.baidu.com/p/1597468718","适合新手练习的几个题目，控制台不再单调呵呵（持续更新）","Geodesic"],
		["http://tieba.baidu.com/p/2025276932","对拼图问题可还原性的探究","忆_碎碎念"],
		["http://tieba.baidu.com/p/2007516908","C语言递归调用转化为栈处理的一般式","elf0223"],
		["http://tieba.baidu.com/p/2092645577","辅助的原理","霸气外露真没有"],
		["http://tieba.baidu.com/p/1313731304","C语言180行随机迷宫代码 详解+分析","追忆曾经_"],
		["http://tieba.baidu.com/p/1360685329","扫雷","wysaid"],
		["http://tieba.baidu.com/p/1972512091","〔九重的百物语之二〕A cellular compiler","守尸神主"],
		["http://tieba.baidu.com/p/1797769781","【新手进阶】话说那些聊天与游戏的网络交互实现","汇蓝鸟"],
		["http://tieba.baidu.com/p/1798139204","【初入老鸟】那些网游外挂中大大小小的远程call","汇蓝鸟"],
		["http://tieba.baidu.com/p/1852969320","【游戏编程】构架游戏中的粒子系统","汇蓝鸟"],
		["http://tieba.baidu.com/p/1795338852","【新手教程】用C语言制作单机游戏外挂","汇蓝鸟"],
		["http://tieba.baidu.com/p/1868393695","【音乐编程】基于DirectSound的音乐播放与FFT频谱可视化(part 1)","汇蓝鸟"],
		["http://tieba.baidu.com/p/1885477077","【音乐编程】基于DirectSound的音乐播放与FFT频谱可视化(part 3)","汇蓝鸟"],
		["http://tieba.baidu.com/p/1906977428","【音乐编程】播放器频谱可视化与语音的智能识别思想(part 3)","汇蓝鸟"],
		["http://tieba.baidu.com/f/good?kw=c%D3%EF%D1%D4","更多请阅读'本吧精品区'",""],
	]},
	{name:"关于二级",init:fill_link,content:[
		["http://tieba.baidu.com/p/1877978397","我们为什么那么痛恨计算机等级与那些问题（二级党请进）","汇蓝鸟"],
		["http://tieba.baidu.com/p/1213185590","建议彻底封杀二级党","serviper"],
	]},
	{name:"关于谭书",init:fill_link,content:[
		["javascript:;","TODO:find something to put here",""],
	]},
	{name:"其他",init:fill_link,content:[
		["http://tieba.baidu.com/p/13382217","原问题资料大全","vc99"],
		["http://tieba.baidu.com/p/1620654727","螺旋方阵","寒云似雾"],
		["http://netlib.bell-labs.com/cm/cs/pearls/index.html","《编程珠玑》(适合有一定数据结构和算法基础的)",""],
		["http://c-faq-chn.sourceforge.net/","C语言常见问题集/495个C语言问题",""],
	]},
	{name:"Credits",init:fill_link,content:[
		["http://tieba.baidu.com/p/1941867601","IRC频道","..."],
		["rox.html","ROX版","RichSelian"],
		["https://github.com/hysw/tieba","本页源码","寒云似雾"],
		["https://github.com/","Hosted on GitHub Pages &mdash; Theme by <a href=\"http://twitter.com/#!/michigangraham\">mattgraham</a>",""],
	]},
]